version: "3.8"
volumes:
  postgres_volume:

services:
  pg-go-db:
    image: postgres:14-alpine3.15
    container_name: "pg-note"
    environment:
      - "POSTGRES_DB=note-service"
      - "POSTGRES_USER=note-service-user"
      - "POSTGRES_PASSWORD=note-service-password"
    ports:
      - "5434:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
